// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `third_party/c-ray/include/c-ray.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FlutterCrayBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterCrayBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterCrayBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// -- Library info --
  ffi.Pointer<ffi.Char> cr_get_version() {
    return _cr_get_version();
  }

  late final _cr_get_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'cr_get_version');
  late final _cr_get_version =
      _cr_get_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> cr_get_git_hash() {
    return _cr_get_git_hash();
  }

  late final _cr_get_git_hashPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'cr_get_git_hash');
  late final _cr_get_git_hash =
      _cr_get_git_hashPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<cr_renderer> cr_new_renderer() {
    return _cr_new_renderer();
  }

  late final _cr_new_rendererPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<cr_renderer> Function()>>(
          'cr_new_renderer');
  late final _cr_new_renderer =
      _cr_new_rendererPtr.asFunction<ffi.Pointer<cr_renderer> Function()>();

  void cr_destroy_renderer(
    ffi.Pointer<cr_renderer> r,
  ) {
    return _cr_destroy_renderer(
      r,
    );
  }

  late final _cr_destroy_rendererPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<cr_renderer>)>>(
          'cr_destroy_renderer');
  late final _cr_destroy_renderer = _cr_destroy_rendererPtr
      .asFunction<void Function(ffi.Pointer<cr_renderer>)>();

  bool cr_renderer_set_callback(
    ffi.Pointer<cr_renderer> ext,
    int t,
    ffi.Pointer<
            ffi.NativeFunction<
                ffi.Void Function(
                    ffi.Pointer<cr_renderer_cb_info>, ffi.Pointer<ffi.Void>)>>
        callback_fn,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _cr_renderer_set_callback(
      ext,
      t,
      callback_fn,
      user_data,
    );
  }

  late final _cr_renderer_set_callbackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(
              ffi.Pointer<cr_renderer>,
              ffi.UnsignedInt,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Void Function(ffi.Pointer<cr_renderer_cb_info>,
                          ffi.Pointer<ffi.Void>)>>,
              ffi.Pointer<ffi.Void>)>>('cr_renderer_set_callback');
  late final _cr_renderer_set_callback =
      _cr_renderer_set_callbackPtr.asFunction<
          bool Function(
              ffi.Pointer<cr_renderer>,
              int,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Void Function(ffi.Pointer<cr_renderer_cb_info>,
                          ffi.Pointer<ffi.Void>)>>,
              ffi.Pointer<ffi.Void>)>();

  bool cr_renderer_set_num_pref(
    ffi.Pointer<cr_renderer> ext,
    int p,
    int num,
  ) {
    return _cr_renderer_set_num_pref(
      ext,
      p,
      num,
    );
  }

  late final _cr_renderer_set_num_prefPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<cr_renderer>, ffi.UnsignedInt,
              ffi.Uint64)>>('cr_renderer_set_num_pref');
  late final _cr_renderer_set_num_pref = _cr_renderer_set_num_prefPtr
      .asFunction<bool Function(ffi.Pointer<cr_renderer>, int, int)>();

  bool cr_renderer_set_str_pref(
    ffi.Pointer<cr_renderer> ext,
    int p,
    ffi.Pointer<ffi.Char> str,
  ) {
    return _cr_renderer_set_str_pref(
      ext,
      p,
      str,
    );
  }

  late final _cr_renderer_set_str_prefPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<cr_renderer>, ffi.UnsignedInt,
              ffi.Pointer<ffi.Char>)>>('cr_renderer_set_str_pref');
  late final _cr_renderer_set_str_pref =
      _cr_renderer_set_str_prefPtr.asFunction<
          bool Function(
              ffi.Pointer<cr_renderer>, int, ffi.Pointer<ffi.Char>)>();

  void cr_renderer_stop(
    ffi.Pointer<cr_renderer> ext,
  ) {
    return _cr_renderer_stop(
      ext,
    );
  }

  late final _cr_renderer_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<cr_renderer>)>>(
          'cr_renderer_stop');
  late final _cr_renderer_stop = _cr_renderer_stopPtr
      .asFunction<void Function(ffi.Pointer<cr_renderer>)>();

  void cr_renderer_restart_interactive(
    ffi.Pointer<cr_renderer> ext,
  ) {
    return _cr_renderer_restart_interactive(
      ext,
    );
  }

  late final _cr_renderer_restart_interactivePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<cr_renderer>)>>(
          'cr_renderer_restart_interactive');
  late final _cr_renderer_restart_interactive =
      _cr_renderer_restart_interactivePtr
          .asFunction<void Function(ffi.Pointer<cr_renderer>)>();

  void cr_renderer_toggle_pause(
    ffi.Pointer<cr_renderer> ext,
  ) {
    return _cr_renderer_toggle_pause(
      ext,
    );
  }

  late final _cr_renderer_toggle_pausePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<cr_renderer>)>>(
          'cr_renderer_toggle_pause');
  late final _cr_renderer_toggle_pause = _cr_renderer_toggle_pausePtr
      .asFunction<void Function(ffi.Pointer<cr_renderer>)>();

  ffi.Pointer<ffi.Char> cr_renderer_get_str_pref(
    ffi.Pointer<cr_renderer> ext,
    int p,
  ) {
    return _cr_renderer_get_str_pref(
      ext,
      p,
    );
  }

  late final _cr_renderer_get_str_prefPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<cr_renderer>,
              ffi.UnsignedInt)>>('cr_renderer_get_str_pref');
  late final _cr_renderer_get_str_pref =
      _cr_renderer_get_str_prefPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<cr_renderer>, int)>();

  int cr_renderer_get_num_pref(
    ffi.Pointer<cr_renderer> ext,
    int p,
  ) {
    return _cr_renderer_get_num_pref(
      ext,
      p,
    );
  }

  late final _cr_renderer_get_num_prefPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<cr_renderer>,
              ffi.UnsignedInt)>>('cr_renderer_get_num_pref');
  late final _cr_renderer_get_num_pref = _cr_renderer_get_num_prefPtr
      .asFunction<int Function(ffi.Pointer<cr_renderer>, int)>();

  void cr_renderer_render(
    ffi.Pointer<cr_renderer> r,
  ) {
    return _cr_renderer_render(
      r,
    );
  }

  late final _cr_renderer_renderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<cr_renderer>)>>(
          'cr_renderer_render');
  late final _cr_renderer_render = _cr_renderer_renderPtr
      .asFunction<void Function(ffi.Pointer<cr_renderer>)>();

  void cr_renderer_start_interactive(
    ffi.Pointer<cr_renderer> ext,
  ) {
    return _cr_renderer_start_interactive(
      ext,
    );
  }

  late final _cr_renderer_start_interactivePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<cr_renderer>)>>(
          'cr_renderer_start_interactive');
  late final _cr_renderer_start_interactive = _cr_renderer_start_interactivePtr
      .asFunction<void Function(ffi.Pointer<cr_renderer>)>();

  ffi.Pointer<cr_bitmap> cr_renderer_get_result(
    ffi.Pointer<cr_renderer> r,
  ) {
    return _cr_renderer_get_result(
      r,
    );
  }

  late final _cr_renderer_get_resultPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<cr_bitmap> Function(
              ffi.Pointer<cr_renderer>)>>('cr_renderer_get_result');
  late final _cr_renderer_get_result = _cr_renderer_get_resultPtr
      .asFunction<ffi.Pointer<cr_bitmap> Function(ffi.Pointer<cr_renderer>)>();

  ffi.Pointer<cr_scene> cr_renderer_scene_get(
    ffi.Pointer<cr_renderer> r,
  ) {
    return _cr_renderer_scene_get(
      r,
    );
  }

  late final _cr_renderer_scene_getPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<cr_scene> Function(
              ffi.Pointer<cr_renderer>)>>('cr_renderer_scene_get');
  late final _cr_renderer_scene_get = _cr_renderer_scene_getPtr
      .asFunction<ffi.Pointer<cr_scene> Function(ffi.Pointer<cr_renderer>)>();

  cr_scene_totals cr_get_scene_totals(
    ffi.Pointer<cr_scene> s_ext,
  ) {
    return _cr_get_scene_totals(
      s_ext,
    );
  }

  late final _cr_get_scene_totalsPtr = _lookup<
          ffi.NativeFunction<cr_scene_totals Function(ffi.Pointer<cr_scene>)>>(
      'cr_get_scene_totals');
  late final _cr_get_scene_totals = _cr_get_scene_totalsPtr
      .asFunction<cr_scene_totals Function(ffi.Pointer<cr_scene>)>();

  int cr_scene_add_sphere(
    ffi.Pointer<cr_scene> s_ext,
    double radius,
  ) {
    return _cr_scene_add_sphere(
      s_ext,
      radius,
    );
  }

  late final _cr_scene_add_spherePtr = _lookup<
      ffi.NativeFunction<
          cr_sphere Function(
              ffi.Pointer<cr_scene>, ffi.Float)>>('cr_scene_add_sphere');
  late final _cr_scene_add_sphere = _cr_scene_add_spherePtr
      .asFunction<int Function(ffi.Pointer<cr_scene>, double)>();

  int cr_scene_vertex_buf_new(
    ffi.Pointer<cr_scene> s_ext,
    cr_vertex_buf_param in1,
  ) {
    return _cr_scene_vertex_buf_new(
      s_ext,
      in1,
    );
  }

  late final _cr_scene_vertex_buf_newPtr = _lookup<
      ffi.NativeFunction<
          cr_vertex_buf Function(ffi.Pointer<cr_scene>,
              cr_vertex_buf_param)>>('cr_scene_vertex_buf_new');
  late final _cr_scene_vertex_buf_new = _cr_scene_vertex_buf_newPtr
      .asFunction<int Function(ffi.Pointer<cr_scene>, cr_vertex_buf_param)>();

  void cr_mesh_bind_vertex_buf(
    ffi.Pointer<cr_scene> s_ext,
    int mesh,
    int buf,
  ) {
    return _cr_mesh_bind_vertex_buf(
      s_ext,
      mesh,
      buf,
    );
  }

  late final _cr_mesh_bind_vertex_bufPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<cr_scene>, cr_mesh,
              cr_vertex_buf)>>('cr_mesh_bind_vertex_buf');
  late final _cr_mesh_bind_vertex_buf = _cr_mesh_bind_vertex_bufPtr
      .asFunction<void Function(ffi.Pointer<cr_scene>, int, int)>();

  void cr_mesh_bind_faces(
    ffi.Pointer<cr_scene> s_ext,
    int mesh,
    ffi.Pointer<cr_face> faces,
    int face_count,
  ) {
    return _cr_mesh_bind_faces(
      s_ext,
      mesh,
      faces,
      face_count,
    );
  }

  late final _cr_mesh_bind_facesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<cr_scene>, cr_mesh,
              ffi.Pointer<cr_face>, ffi.Size)>>('cr_mesh_bind_faces');
  late final _cr_mesh_bind_faces = _cr_mesh_bind_facesPtr.asFunction<
      void Function(ffi.Pointer<cr_scene>, int, ffi.Pointer<cr_face>, int)>();

  int cr_scene_mesh_new(
    ffi.Pointer<cr_scene> s_ext,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _cr_scene_mesh_new(
      s_ext,
      name,
    );
  }

  late final _cr_scene_mesh_newPtr = _lookup<
      ffi.NativeFunction<
          cr_mesh Function(ffi.Pointer<cr_scene>,
              ffi.Pointer<ffi.Char>)>>('cr_scene_mesh_new');
  late final _cr_scene_mesh_new = _cr_scene_mesh_newPtr
      .asFunction<int Function(ffi.Pointer<cr_scene>, ffi.Pointer<ffi.Char>)>();

  int cr_scene_get_mesh(
    ffi.Pointer<cr_scene> s_ext,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _cr_scene_get_mesh(
      s_ext,
      name,
    );
  }

  late final _cr_scene_get_meshPtr = _lookup<
      ffi.NativeFunction<
          cr_mesh Function(ffi.Pointer<cr_scene>,
              ffi.Pointer<ffi.Char>)>>('cr_scene_get_mesh');
  late final _cr_scene_get_mesh = _cr_scene_get_meshPtr
      .asFunction<int Function(ffi.Pointer<cr_scene>, ffi.Pointer<ffi.Char>)>();

  int cr_camera_new(
    ffi.Pointer<cr_scene> ext,
  ) {
    return _cr_camera_new(
      ext,
    );
  }

  late final _cr_camera_newPtr =
      _lookup<ffi.NativeFunction<cr_camera Function(ffi.Pointer<cr_scene>)>>(
          'cr_camera_new');
  late final _cr_camera_new =
      _cr_camera_newPtr.asFunction<int Function(ffi.Pointer<cr_scene>)>();

  bool cr_camera_set_num_pref(
    ffi.Pointer<cr_scene> ext,
    int c,
    int p,
    double num,
  ) {
    return _cr_camera_set_num_pref(
      ext,
      c,
      p,
      num,
    );
  }

  late final _cr_camera_set_num_prefPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<cr_scene>, cr_camera, ffi.UnsignedInt,
              ffi.Double)>>('cr_camera_set_num_pref');
  late final _cr_camera_set_num_pref = _cr_camera_set_num_prefPtr
      .asFunction<bool Function(ffi.Pointer<cr_scene>, int, int, double)>();

  double cr_camera_get_num_pref(
    ffi.Pointer<cr_scene> ext,
    int c,
    int p,
  ) {
    return _cr_camera_get_num_pref(
      ext,
      c,
      p,
    );
  }

  late final _cr_camera_get_num_prefPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Pointer<cr_scene>, cr_camera,
              ffi.UnsignedInt)>>('cr_camera_get_num_pref');
  late final _cr_camera_get_num_pref = _cr_camera_get_num_prefPtr
      .asFunction<double Function(ffi.Pointer<cr_scene>, int, int)>();

  bool cr_camera_update(
    ffi.Pointer<cr_scene> ext,
    int c,
  ) {
    return _cr_camera_update(
      ext,
      c,
    );
  }

  late final _cr_camera_updatePtr = _lookup<
          ffi
          .NativeFunction<ffi.Bool Function(ffi.Pointer<cr_scene>, cr_camera)>>(
      'cr_camera_update');
  late final _cr_camera_update = _cr_camera_updatePtr
      .asFunction<bool Function(ffi.Pointer<cr_scene>, int)>();

  int cr_scene_new_material_set(
    ffi.Pointer<cr_scene> s_ext,
  ) {
    return _cr_scene_new_material_set(
      s_ext,
    );
  }

  late final _cr_scene_new_material_setPtr = _lookup<
          ffi.NativeFunction<cr_material_set Function(ffi.Pointer<cr_scene>)>>(
      'cr_scene_new_material_set');
  late final _cr_scene_new_material_set = _cr_scene_new_material_setPtr
      .asFunction<int Function(ffi.Pointer<cr_scene>)>();

  int cr_material_set_add(
    ffi.Pointer<cr_scene> s_ext,
    int set1,
    ffi.Pointer<cr_shader_node> desc,
  ) {
    return _cr_material_set_add(
      s_ext,
      set1,
      desc,
    );
  }

  late final _cr_material_set_addPtr = _lookup<
      ffi.NativeFunction<
          cr_material Function(ffi.Pointer<cr_scene>, cr_material_set,
              ffi.Pointer<cr_shader_node>)>>('cr_material_set_add');
  late final _cr_material_set_add = _cr_material_set_addPtr.asFunction<
      int Function(ffi.Pointer<cr_scene>, int, ffi.Pointer<cr_shader_node>)>();

  void cr_material_update(
    ffi.Pointer<cr_scene> s_ext,
    int set1,
    int mat,
    ffi.Pointer<cr_shader_node> desc,
  ) {
    return _cr_material_update(
      s_ext,
      set1,
      mat,
      desc,
    );
  }

  late final _cr_material_updatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<cr_scene>, cr_material_set, cr_material,
              ffi.Pointer<cr_shader_node>)>>('cr_material_update');
  late final _cr_material_update = _cr_material_updatePtr.asFunction<
      void Function(
          ffi.Pointer<cr_scene>, int, int, ffi.Pointer<cr_shader_node>)>();

  int cr_instance_new(
    ffi.Pointer<cr_scene> s_ext,
    int object,
    int type,
  ) {
    return _cr_instance_new(
      s_ext,
      object,
      type,
    );
  }

  late final _cr_instance_newPtr = _lookup<
      ffi.NativeFunction<
          cr_instance Function(ffi.Pointer<cr_scene>, cr_object,
              ffi.UnsignedInt)>>('cr_instance_new');
  late final _cr_instance_new = _cr_instance_newPtr
      .asFunction<int Function(ffi.Pointer<cr_scene>, int, int)>();

  void cr_instance_set_transform(
    ffi.Pointer<cr_scene> s_ext,
    int instance,
    ffi.Pointer<ffi.Pointer<ffi.Float>> row_major,
  ) {
    return _cr_instance_set_transform(
      s_ext,
      instance,
      row_major,
    );
  }

  late final _cr_instance_set_transformPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<cr_scene>, cr_instance,
                  ffi.Pointer<ffi.Pointer<ffi.Float>>)>>(
      'cr_instance_set_transform');
  late final _cr_instance_set_transform =
      _cr_instance_set_transformPtr.asFunction<
          void Function(ffi.Pointer<cr_scene>, int,
              ffi.Pointer<ffi.Pointer<ffi.Float>>)>();

  void cr_instance_transform(
    ffi.Pointer<cr_scene> s_ext,
    int instance,
    ffi.Pointer<ffi.Pointer<ffi.Float>> row_major,
  ) {
    return _cr_instance_transform(
      s_ext,
      instance,
      row_major,
    );
  }

  late final _cr_instance_transformPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<cr_scene>, cr_instance,
              ffi.Pointer<ffi.Pointer<ffi.Float>>)>>('cr_instance_transform');
  late final _cr_instance_transform = _cr_instance_transformPtr.asFunction<
      void Function(
          ffi.Pointer<cr_scene>, int, ffi.Pointer<ffi.Pointer<ffi.Float>>)>();

  bool cr_instance_bind_material_set(
    ffi.Pointer<cr_scene> s_ext,
    int instance,
    int set1,
  ) {
    return _cr_instance_bind_material_set(
      s_ext,
      instance,
      set1,
    );
  }

  late final _cr_instance_bind_material_setPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<cr_scene>, cr_instance,
              cr_material_set)>>('cr_instance_bind_material_set');
  late final _cr_instance_bind_material_set = _cr_instance_bind_material_setPtr
      .asFunction<bool Function(ffi.Pointer<cr_scene>, int, int)>();

  /// -- Misc. --
  bool cr_scene_set_background(
    ffi.Pointer<cr_scene> s_ext,
    ffi.Pointer<cr_shader_node> desc,
  ) {
    return _cr_scene_set_background(
      s_ext,
      desc,
    );
  }

  late final _cr_scene_set_backgroundPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<cr_scene>,
              ffi.Pointer<cr_shader_node>)>>('cr_scene_set_background');
  late final _cr_scene_set_background = _cr_scene_set_backgroundPtr.asFunction<
      bool Function(ffi.Pointer<cr_scene>, ffi.Pointer<cr_shader_node>)>();

  void cr_start_render_worker(
    int port,
    int thread_limit,
  ) {
    return _cr_start_render_worker(
      port,
      thread_limit,
    );
  }

  late final _cr_start_render_workerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Size)>>(
          'cr_start_render_worker');
  late final _cr_start_render_worker =
      _cr_start_render_workerPtr.asFunction<void Function(int, int)>();

  void cr_send_shutdown_to_workers(
    ffi.Pointer<ffi.Char> node_list,
  ) {
    return _cr_send_shutdown_to_workers(
      node_list,
    );
  }

  late final _cr_send_shutdown_to_workersPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'cr_send_shutdown_to_workers');
  late final _cr_send_shutdown_to_workers = _cr_send_shutdown_to_workersPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  bool cr_load_json(
    ffi.Pointer<cr_renderer> r_ext,
    ffi.Pointer<ffi.Char> file_path,
  ) {
    return _cr_load_json(
      r_ext,
      file_path,
    );
  }

  late final _cr_load_jsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<cr_renderer>,
              ffi.Pointer<ffi.Char>)>>('cr_load_json');
  late final _cr_load_json = _cr_load_jsonPtr.asFunction<
      bool Function(ffi.Pointer<cr_renderer>, ffi.Pointer<ffi.Char>)>();

  void cr_log_level_set(
    int arg0,
  ) {
    return _cr_log_level_set(
      arg0,
    );
  }

  late final _cr_log_level_setPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UnsignedInt)>>(
          'cr_log_level_set');
  late final _cr_log_level_set =
      _cr_log_level_setPtr.asFunction<void Function(int)>();

  int cr_log_level_get() {
    return _cr_log_level_get();
  }

  late final _cr_log_level_getPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function()>>(
          'cr_log_level_get');
  late final _cr_log_level_get =
      _cr_log_level_getPtr.asFunction<int Function()>();

  void cr_debug_dump_state(
    ffi.Pointer<cr_renderer> r_ext,
  ) {
    return _cr_debug_dump_state(
      r_ext,
    );
  }

  late final _cr_debug_dump_statePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<cr_renderer>)>>(
          'cr_debug_dump_state');
  late final _cr_debug_dump_state = _cr_debug_dump_statePtr
      .asFunction<void Function(ffi.Pointer<cr_renderer>)>();
}

/// -- Renderer --
final class cr_renderer extends ffi.Opaque {}

sealed class cr_renderer_param {
  /// Num
  static const cr_renderer_threads = 0;
  static const cr_renderer_samples = 1;
  static const cr_renderer_bounces = 2;
  static const cr_renderer_tile_width = 3;
  static const cr_renderer_tile_height = 4;
  static const cr_renderer_tile_order = 5;
  static const cr_renderer_output_num = 6;
  static const cr_renderer_override_width = 7;
  static const cr_renderer_override_height = 8;
  static const cr_renderer_override_cam = 9;
  static const cr_renderer_is_iterative = 10;

  /// String
  static const cr_renderer_output_path = 11;
  static const cr_renderer_asset_path = 12;
  static const cr_renderer_output_name = 13;
  static const cr_renderer_output_filetype = 14;
  static const cr_renderer_node_list = 15;
  static const cr_renderer_blender_mode = 16;
}

sealed class cr_tile_state {
  static const cr_tile_ready_to_render = 0;
  static const cr_tile_rendering = 1;
  static const cr_tile_finished = 2;
}

final class cr_tile extends ffi.Struct {
  @ffi.Int()
  external int w;

  @ffi.Int()
  external int h;

  @ffi.Int()
  external int start_x;

  @ffi.Int()
  external int start_y;

  @ffi.Int()
  external int end_x;

  @ffi.Int()
  external int end_y;

  @ffi.UnsignedInt()
  external int state;

  @ffi.Bool()
  external bool network_renderer;

  @ffi.Int()
  external int index;

  @ffi.Size()
  external int total_samples;

  @ffi.Size()
  external int completed_samples;
}

sealed class cr_bm_colorspace {
  static const cr_bm_linear = 0;
  static const cr_bm_sRGB = 1;
}

sealed class cr_bm_channel_precision {
  static const cr_bm_char = 0;
  static const cr_bm_float = 1;
}

final class UnnamedUnion1 extends ffi.Union {
  external ffi.Pointer<ffi.UnsignedChar> byte_ptr;

  external ffi.Pointer<ffi.Float> float_ptr;
}

final class cr_bitmap extends ffi.Struct {
  @ffi.UnsignedInt()
  external int colorspace;

  @ffi.UnsignedInt()
  external int precision;

  external UnnamedUnion1 data;

  @ffi.Size()
  external int stride;

  @ffi.Size()
  external int width;

  @ffi.Size()
  external int height;
}

final class cr_renderer_cb_info extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<cr_bitmap>> fb;

  external ffi.Pointer<cr_tile> tiles;

  @ffi.Size()
  external int tiles_count;

  @ffi.Size()
  external int active_threads;

  @ffi.Double()
  external double avg_per_ray_us;

  @ffi.Int64()
  external int samples_per_sec;

  @ffi.Int64()
  external int eta_ms;

  @ffi.Size()
  external int finished_passes;

  @ffi.Double()
  external double completion;

  @ffi.Bool()
  external bool paused;
}

sealed class cr_renderer_callback {
  static const cr_cb_on_start = 0;
  static const cr_cb_on_stop = 1;
  static const cr_cb_status_update = 2;
  static const cr_cb_on_state_changed = 3;
  static const cr_cb_on_interactive_pass_finished = 4;
}

/// -- Scene --
final class cr_vector extends ffi.Struct {
  @ffi.Float()
  external double x;

  @ffi.Float()
  external double y;

  @ffi.Float()
  external double z;
}

final class cr_coord extends ffi.Struct {
  @ffi.Float()
  external double u;

  @ffi.Float()
  external double v;
}

final class cr_scene extends ffi.Opaque {}

final class cr_scene_totals extends ffi.Struct {
  @ffi.Size()
  external int meshes;

  @ffi.Size()
  external int spheres;

  @ffi.Size()
  external int instances;

  @ffi.Size()
  external int cameras;
}

final class cr_color extends ffi.Struct {
  @ffi.Float()
  external double r;

  @ffi.Float()
  external double g;

  @ffi.Float()
  external double b;

  @ffi.Float()
  external double a;
}

typedef cr_object = ffi.Int64;
typedef Dartcr_object = int;
typedef cr_sphere = cr_object;
typedef cr_mesh = cr_object;

final class cr_vertex_buf_param extends ffi.Struct {
  external ffi.Pointer<cr_vector> vertices;

  @ffi.Size()
  external int vertex_count;

  external ffi.Pointer<cr_vector> normals;

  @ffi.Size()
  external int normal_count;

  external ffi.Pointer<cr_coord> tex_coords;

  @ffi.Size()
  external int tex_coord_count;
}

typedef cr_vertex_buf = cr_object;

final class cr_face extends ffi.Struct {
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Int> vertex_idx;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Int> normal_idx;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Int> texture_idx;

  @ffi.Uint16()
  external int mat_idx;

  @ffi.Bool()
  external bool has_normals;
}

/// -- Camera --
/// FIXME: Use cr_vector
/// TODO: Support quaternions, or maybe just a mtx4x4?
sealed class cr_camera_param {
  static const cr_camera_fov = 0;
  static const cr_camera_focus_distance = 1;
  static const cr_camera_fstops = 2;
  static const cr_camera_pose_x = 3;
  static const cr_camera_pose_y = 4;
  static const cr_camera_pose_z = 5;
  static const cr_camera_pose_roll = 6;
  static const cr_camera_pose_pitch = 7;
  static const cr_camera_pose_yaw = 8;
  static const cr_camera_time = 9;
  static const cr_camera_res_x = 10;
  static const cr_camera_res_y = 11;
  static const cr_camera_blender_coord = 12;
}

typedef cr_camera = cr_object;
typedef cr_material_set = cr_object;
typedef cr_material = cr_object;

sealed class cr_shader_node_type {
  static const cr_bsdf_unknown = 0;
  static const cr_bsdf_diffuse = 1;
  static const cr_bsdf_metal = 2;
  static const cr_bsdf_glass = 3;
  static const cr_bsdf_plastic = 4;
  static const cr_bsdf_mix = 5;
  static const cr_bsdf_add = 6;
  static const cr_bsdf_transparent = 7;
  static const cr_bsdf_emissive = 8;
  static const cr_bsdf_translucent = 9;
  static const cr_bsdf_background = 10;
}

enum color_node_type {
  cr_cn_unknown(0),
  cr_cn_constant(1),
  cr_cn_image(2),
  cr_cn_checkerboard(3),
  cr_cn_blackbody(4),
  cr_cn_split(5),
  cr_cn_rgb(6),
  cr_cn_hsl(7),
  cr_cn_hsv(8),
  cr_cn_hsv_tform(9),
  cr_cn_vec_to_color(10),
  cr_cn_gradient(11),
  cr_cn_color_mix(12),
  cr_cn_color_ramp(13);

  final int value;
  const color_node_type(this.value);

  static color_node_type fromValue(int value) => switch (value) {
        0 => cr_cn_unknown,
        1 => cr_cn_constant,
        2 => cr_cn_image,
        3 => cr_cn_checkerboard,
        4 => cr_cn_blackbody,
        5 => cr_cn_split,
        6 => cr_cn_rgb,
        7 => cr_cn_hsl,
        8 => cr_cn_hsv,
        9 => cr_cn_hsv_tform,
        10 => cr_cn_vec_to_color,
        11 => cr_cn_gradient,
        12 => cr_cn_color_mix,
        13 => cr_cn_color_ramp,
        _ => throw ArgumentError("Unknown value for color_node_type: $value"),
      };
}

final class cr_image_texture_params extends ffi.Struct {
  external ffi.Pointer<ffi.Char> full_path;

  @ffi.Uint8()
  external int options;
}

sealed class cr_value_node_type {
  static const cr_vn_unknown = 0;
  static const cr_vn_constant = 1;
  static const cr_vn_fresnel = 2;
  static const cr_vn_map_range = 3;
  static const cr_vn_light_path = 4;
  static const cr_vn_alpha = 5;
  static const cr_vn_vec_to_value = 6;
  static const cr_vn_math = 7;
  static const cr_vn_grayscale = 8;
}

sealed class cr_vector_node_type {
  static const cr_vec_unknown = 0;
  static const cr_vec_constant = 1;
  static const cr_vec_normal = 2;
  static const cr_vec_uv = 3;
  static const cr_vec_vecmath = 4;
  static const cr_vec_mix = 5;
  static const cr_vec_from_color = 6;
}

/// These are ripped off here:
/// https://docs.blender.org/manual/en/latest/render/shader_nodes/converter/vector_math.html
/// TODO: Commented ones need to be implemented to reach parity with Cycles. Feel free to do so! :^)
sealed class cr_vec_op {
  static const VecAdd = 0;
  static const VecSubtract = 1;
  static const VecMultiply = 2;
  static const VecDivide = 3;

  /// VecMultiplyAdd,
  static const VecCross = 4;

  /// VecProject,
  static const VecReflect = 5;
  static const VecRefract = 6;

  /// VecFaceforward,
  static const VecDot = 7;
  static const VecDistance = 8;
  static const VecLength = 9;
  static const VecScale = 10;
  static const VecNormalize = 11;
  static const VecWrap = 12;

  /// VecSnap,
  static const VecFloor = 13;
  static const VecCeil = 14;
  static const VecModulo = 15;

  /// VecFraction,
  static const VecAbs = 16;
  static const VecMin = 17;
  static const VecMax = 18;
  static const VecSin = 19;
  static const VecCos = 20;
  static const VecTan = 21;
}

final class cr_vecmath_params extends ffi.Struct {
  external ffi.Pointer<cr_vector_node> A;

  external ffi.Pointer<cr_vector_node> B;

  external ffi.Pointer<cr_vector_node> C;

  external ffi.Pointer<cr_value_node> f;

  @ffi.UnsignedInt()
  external int op;
}

final class cr_vec_mix_params extends ffi.Struct {
  external ffi.Pointer<cr_vector_node> A;

  external ffi.Pointer<cr_vector_node> B;

  external ffi.Pointer<cr_value_node> factor;
}

final class cr_vec_from_color_params extends ffi.Struct {
  external ffi.Pointer<cr_color_node> C;
}

/// TODO: Maybe express vectorValue vec/coord/float union a bit better here?
final class UnnamedUnion5 extends ffi.Union {
  external cr_vector constant;

  external cr_vecmath_params vecmath;

  external cr_vec_mix_params vec_mix;

  external cr_vec_from_color_params vec_from_color;
}

final class cr_vector_node extends ffi.Struct {
  @ffi.UnsignedInt()
  external int type;

  external UnnamedUnion5 arg;
}

final class cr_fresnel_params extends ffi.Struct {
  external ffi.Pointer<cr_value_node> IOR;

  external ffi.Pointer<cr_vector_node> normal;
}

final class cr_map_range_params extends ffi.Struct {
  external ffi.Pointer<cr_value_node> input_value;

  external ffi.Pointer<cr_value_node> from_min;

  external ffi.Pointer<cr_value_node> from_max;

  external ffi.Pointer<cr_value_node> to_min;

  external ffi.Pointer<cr_value_node> to_max;
}

sealed class cr_light_path_info {
  static const cr_is_camera_ray = 0;
  static const cr_is_shadow_ray = 1;
  static const cr_is_diffuse_ray = 2;
  static const cr_is_glossy_ray = 3;
  static const cr_is_singular_ray = 4;
  static const cr_is_reflection_ray = 5;
  static const cr_is_transmission_ray = 6;
  static const cr_ray_length = 7;
}

final class cr_light_path_params extends ffi.Struct {
  @ffi.UnsignedInt()
  external int query;
}

final class cr_alpha_params extends ffi.Struct {
  external ffi.Pointer<cr_color_node> color;
}

sealed class cr_vec_to_value_component {
  static const X = 0;
  static const Y = 1;
  static const Z = 2;
  static const U = 3;
  static const V = 4;
  static const F = 5;
}

final class cr_vec_to_value_params extends ffi.Struct {
  @ffi.UnsignedInt()
  external int comp;

  external ffi.Pointer<cr_vector_node> vec;
}

/// These are ripped off here:
/// https://docs.blender.org/manual/en/latest/render/shader_nodes/converter/math.html
/// TODO: Commented ones need to be implemented to reach parity with Cycles. Feel free to do so! :^)
sealed class cr_math_op {
  static const Add = 0;
  static const Subtract = 1;
  static const Multiply = 2;
  static const Divide = 3;

  /// MultiplyAdd,
  static const Power = 4;
  static const Log = 5;
  static const SquareRoot = 6;
  static const InvSquareRoot = 7;
  static const Absolute = 8;

  /// Exponent,
  static const Min = 9;
  static const Max = 10;
  static const LessThan = 11;
  static const GreaterThan = 12;
  static const Sign = 13;
  static const Compare = 14;

  /// SmoothMin,
  /// SmoothMax,
  static const Round = 15;
  static const Floor = 16;
  static const Ceil = 17;
  static const Truncate = 18;
  static const Fraction = 19;
  static const Modulo = 20;

  /// Wrap,
  /// Snap,
  /// PingPong,
  static const Sine = 21;
  static const Cosine = 22;
  static const Tangent = 23;

  /// ArcSine,
  /// ArcCosine,
  /// ArcTangent,
  /// ArcTan2,
  /// HyperbolicSine,
  /// HyperbolicCosine,
  /// HyperbolicTangent,
  static const ToRadians = 24;
  static const ToDegrees = 25;
}

final class cr_math_params extends ffi.Struct {
  external ffi.Pointer<cr_value_node> A;

  external ffi.Pointer<cr_value_node> B;

  @ffi.UnsignedInt()
  external int op;
}

final class cr_grayscale_params extends ffi.Struct {
  external ffi.Pointer<cr_color_node> color;
}

final class UnnamedUnion4 extends ffi.Union {
  @ffi.Double()
  external double constant;

  external cr_fresnel_params fresnel;

  external cr_map_range_params map_range;

  external cr_light_path_params light_path;

  external cr_alpha_params alpha;

  external cr_vec_to_value_params vec_to_value;

  external cr_math_params math;

  external cr_grayscale_params grayscale;
}

final class cr_value_node extends ffi.Struct {
  @ffi.UnsignedInt()
  external int type;

  external UnnamedUnion4 arg;
}

final class cr_checkerboard_params extends ffi.Struct {
  external ffi.Pointer<cr_color_node> a;

  external ffi.Pointer<cr_color_node> b;

  external ffi.Pointer<cr_value_node> scale;
}

final class cr_blackbody_params extends ffi.Struct {
  external ffi.Pointer<cr_value_node> degrees;
}

final class cr_split_params extends ffi.Struct {
  external ffi.Pointer<cr_value_node> node;
}

final class cr_rgb_params extends ffi.Struct {
  external ffi.Pointer<cr_value_node> red;

  external ffi.Pointer<cr_value_node> green;

  external ffi.Pointer<cr_value_node> blue;
}

final class cr_hsl_params extends ffi.Struct {
  external ffi.Pointer<cr_value_node> H;

  external ffi.Pointer<cr_value_node> S;

  external ffi.Pointer<cr_value_node> L;
}

final class cr_hsv_params extends ffi.Struct {
  external ffi.Pointer<cr_value_node> H;

  external ffi.Pointer<cr_value_node> S;

  external ffi.Pointer<cr_value_node> V;
}

final class cr_hsv_tform_params extends ffi.Struct {
  external ffi.Pointer<cr_color_node> tex;

  external ffi.Pointer<cr_value_node> H;

  external ffi.Pointer<cr_value_node> S;

  external ffi.Pointer<cr_value_node> V;

  external ffi.Pointer<cr_value_node> f;
}

final class cr_vec_to_color_params extends ffi.Struct {
  external ffi.Pointer<cr_vector_node> vec;
}

final class cr_gradient_params extends ffi.Struct {
  external ffi.Pointer<cr_color_node> a;

  external ffi.Pointer<cr_color_node> b;
}

final class cr_color_mix_params extends ffi.Struct {
  external ffi.Pointer<cr_color_node> a;

  external ffi.Pointer<cr_color_node> b;

  external ffi.Pointer<cr_value_node> factor;
}

sealed class cr_color_mode {
  static const cr_mode_rgb = 0;
  static const cr_mode_hsv = 1;
  static const cr_mode_hsl = 2;
}

sealed class cr_interpolation {
  /// TODO
  static const cr_ease = 0;

  /// TODO
  static const cr_cardinal = 1;
  static const cr_linear = 2;

  /// TODO
  static const cr_b_spline = 3;
  static const cr_constant = 4;
}

final class ramp_element extends ffi.Struct {
  external cr_color color;

  /// [0.0,1.0]
  @ffi.Float()
  external double position;
}

final class cr_color_ramp_params extends ffi.Struct {
  external ffi.Pointer<cr_value_node> factor;

  @ffi.UnsignedInt()
  external int color_mode;

  @ffi.UnsignedInt()
  external int interpolation;

  external ffi.Pointer<ramp_element> elements;

  @ffi.Int()
  external int element_count;
}

final class UnnamedUnion3 extends ffi.Union {
  external cr_color constant;

  external cr_image_texture_params image;

  external cr_checkerboard_params checkerboard;

  external cr_blackbody_params blackbody;

  external cr_split_params split;

  external cr_rgb_params rgb;

  external cr_hsl_params hsl;

  external cr_hsv_params hsv;

  external cr_hsv_tform_params hsv_tform;

  external cr_vec_to_color_params vec_to_color;

  external cr_gradient_params gradient;

  external cr_color_mix_params color_mix;

  external cr_color_ramp_params color_ramp;
}

/// ------
final class cr_color_node extends ffi.Struct {
  @ffi.UnsignedInt()
  external int typeAsInt;

  color_node_type get type => color_node_type.fromValue(typeAsInt);

  external UnnamedUnion3 arg;
}

final class cr_diffuse_args extends ffi.Struct {
  external ffi.Pointer<cr_color_node> color;
}

final class cr_metal_args extends ffi.Struct {
  external ffi.Pointer<cr_color_node> color;

  external ffi.Pointer<cr_value_node> roughness;
}

final class cr_glass_args extends ffi.Struct {
  external ffi.Pointer<cr_color_node> color;

  external ffi.Pointer<cr_value_node> roughness;

  external ffi.Pointer<cr_value_node> IOR;
}

final class cr_plastic_args extends ffi.Struct {
  external ffi.Pointer<cr_color_node> color;

  external ffi.Pointer<cr_value_node> roughness;

  external ffi.Pointer<cr_value_node> IOR;
}

final class cr_mix_args extends ffi.Struct {
  external ffi.Pointer<cr_shader_node> A;

  external ffi.Pointer<cr_shader_node> B;

  external ffi.Pointer<cr_value_node> factor;
}

final class cr_add_args extends ffi.Struct {
  external ffi.Pointer<cr_shader_node> A;

  external ffi.Pointer<cr_shader_node> B;
}

final class cr_transparent_args extends ffi.Struct {
  external ffi.Pointer<cr_color_node> color;
}

final class cr_emissive_args extends ffi.Struct {
  external ffi.Pointer<cr_color_node> color;

  external ffi.Pointer<cr_value_node> strength;
}

final class cr_translucent_args extends ffi.Struct {
  external ffi.Pointer<cr_color_node> color;
}

final class cr_background_args extends ffi.Struct {
  external ffi.Pointer<cr_color_node> color;

  external ffi.Pointer<cr_vector_node> pose;

  external ffi.Pointer<cr_value_node> strength;
}

final class UnnamedUnion2 extends ffi.Union {
  external cr_diffuse_args diffuse;

  external cr_metal_args metal;

  external cr_glass_args glass;

  external cr_plastic_args plastic;

  external cr_mix_args mix;

  external cr_add_args add;

  external cr_transparent_args transparent;

  external cr_emissive_args emissive;

  external cr_translucent_args translucent;

  external cr_background_args background;
}

final class cr_shader_node extends ffi.Struct {
  @ffi.UnsignedInt()
  external int type;

  external UnnamedUnion2 arg;
}

/// -- Instancing --
typedef cr_instance = ffi.Int64;
typedef Dartcr_instance = int;

sealed class cr_object_type {
  static const cr_object_mesh = 0;
  static const cr_object_sphere = 1;
}

sealed class cr_log_level {
  static const Silent = 0;
  static const Info = 1;
  static const Debug = 2;
  static const Spam = 3;
}

const int C_RAY_PROTO_DEFAULT_PORT = 2222;

const int MAX_CRAY_VERTEX_COUNT = 3;
